import type { Dispatch, ReactNode, SetStateAction } from "react";
import type { EditableActionGroup } from "../api";
import { AzurePlacementFields, AzureResourceDropdown } from "./AlertsAuthoringSelectors";

type AdvancedKey =
  | "voice_receivers"
  | "azure_app_push_receivers"
  | "azure_function_receivers"
  | "logic_app_receivers"
  | "event_hub_receivers"
  | "automation_runbook_receivers"
  | "itsm_receivers";

const input = "rounded border px-2 py-1.5";

export function AdvancedActionGroupReceivers({ value, connectionId, setValue }: { value: EditableActionGroup; connectionId: string; setValue: Dispatch<SetStateAction<EditableActionGroup>> }) {
  function update<K extends AdvancedKey>(key: K, index: number, patch: Partial<EditableActionGroup[K][number]>) {
    setValue((current) => ({ ...current, [key]: current[key].map((item, i) => i === index ? { ...item, ...patch } : item) }));
  }
  function remove(key: AdvancedKey, index: number) {
    setValue((current) => ({ ...current, [key]: current[key].filter((_item, i) => i !== index) }));
  }
  return <div className="space-y-3">
    <div className="rounded border border-indigo-200 bg-indigo-50 px-3 py-2 text-indigo-800"><strong>Advanced delivery channels</strong><div className="text-[10px]">Signed Function, Logic App, and Runbook endpoints and ITSM ticket configuration stay hidden and are preserved unless replaced.</div></div>
    {value.webhook_receivers.length > 0 && <section className="space-y-2 rounded-lg border p-3"><h3 className="font-semibold text-gray-800">Secure webhook authentication</h3><p className="text-[10px] text-gray-500">Optionally authenticate each webhook with Microsoft Entra ID.</p>{value.webhook_receivers.map((item, i) => <div key={i} className="grid gap-2 rounded bg-gray-50 p-2 sm:grid-cols-2"><label className="flex items-center gap-2"><input type="checkbox" checked={!!item.use_aad_auth} onChange={(e) => setValue((current) => ({ ...current, webhook_receivers: current.webhook_receivers.map((entry, index) => index === i ? { ...entry, use_aad_auth: e.target.checked } : entry) }))} /> {item.name || `Webhook ${i + 1}`} uses Entra authentication</label>{item.use_aad_auth && <><input aria-label="Secure webhook object ID" placeholder="Application object GUID" value={item.object_id || ""} onChange={(e) => setValue((current) => ({ ...current, webhook_receivers: current.webhook_receivers.map((entry, index) => index === i ? { ...entry, object_id: e.target.value } : entry) }))} className={input} /><input aria-label="Secure webhook tenant ID" placeholder="Tenant GUID" value={item.tenant_id || ""} onChange={(e) => setValue((current) => ({ ...current, webhook_receivers: current.webhook_receivers.map((entry, index) => index === i ? { ...entry, tenant_id: e.target.value } : entry) }))} className={input} /><input aria-label="Secure webhook identifier URI" placeholder="api://application-id or App ID URI" value={item.identifier_uri || ""} onChange={(e) => setValue((current) => ({ ...current, webhook_receivers: current.webhook_receivers.map((entry, index) => index === i ? { ...entry, identifier_uri: e.target.value } : entry) }))} className={input} /></>}</div>)}</section>}
    <Section title="Voice receivers" onAdd={() => setValue({ ...value, voice_receivers: [...value.voice_receivers, { name: "", country_code: "1", phone_number: "" }] })}>{value.voice_receivers.map((item, i) => <div key={i} className="grid gap-2 sm:grid-cols-[1fr_100px_2fr_auto]"><input aria-label="Voice receiver name" placeholder="Name" value={item.name} onChange={(e) => update("voice_receivers", i, { name: e.target.value })} className={input} /><input aria-label="Voice country code" placeholder="1" value={item.country_code} onChange={(e) => update("voice_receivers", i, { country_code: e.target.value })} className={input} /><input aria-label="Voice phone number" placeholder="Phone number" value={item.phone_number} onChange={(e) => update("voice_receivers", i, { phone_number: e.target.value })} className={input} /><button onClick={() => remove("voice_receivers", i)} className="text-red-600">Remove</button></div>)}</Section>
    <Section title="Azure mobile app push" onAdd={() => setValue({ ...value, azure_app_push_receivers: [...value.azure_app_push_receivers, { name: "", email_address: "" }] })}>{value.azure_app_push_receivers.map((item, i) => <div key={i} className="grid gap-2 sm:grid-cols-[1fr_2fr_auto]"><input aria-label="Push receiver name" placeholder="Name" value={item.name} onChange={(e) => update("azure_app_push_receivers", i, { name: e.target.value })} className={input} /><input aria-label="Push email address" placeholder="name@example.com" value={item.email_address} onChange={(e) => update("azure_app_push_receivers", i, { email_address: e.target.value })} className={input} /><button onClick={() => remove("azure_app_push_receivers", i)} className="text-red-600">Remove</button></div>)}</Section>
    <Section title="Azure Functions" onAdd={() => setValue({ ...value, azure_function_receivers: [...value.azure_function_receivers, { name: "", function_app_resource_id: "", function_name: "", endpoint: "", preserve_secret: false, use_common_alert_schema: true }] })}>{value.azure_function_receivers.map((item, i) => <EndpointRow key={i} name={item.name} nameLabel="Function receiver name" resourceId={item.function_app_resource_id} resourceLabel="Function App" resourcePlaceholder="" endpoint={item.endpoint} preserveSecret={item.preserve_secret} common={item.use_common_alert_schema} resourceControl={<AzureResourceDropdown label="Function App" connectionId={connectionId} subscriptionId={value.subscription_id} resourceGroup={value.resource_group} types={["microsoft.web/sites"]} value={item.function_app_resource_id} onChange={(function_app_resource_id) => update("azure_function_receivers", i, { function_app_resource_id, function_name: "" })} />} extra={<AzureResourceDropdown label="Function" connectionId={connectionId} subscriptionId={value.subscription_id} resourceGroup={value.resource_group} types={["microsoft.web/sites/functions"]} value={item.function_name} valueMode="name" onChange={(function_name) => update("azure_function_receivers", i, { function_name })} />} onName={(name) => update("azure_function_receivers", i, { name })} onResource={(function_app_resource_id) => update("azure_function_receivers", i, { function_app_resource_id })} onEndpoint={(endpoint) => update("azure_function_receivers", i, { endpoint, preserve_secret: false })} onCommon={(use_common_alert_schema) => update("azure_function_receivers", i, { use_common_alert_schema })} onRemove={() => remove("azure_function_receivers", i)} />)}</Section>
    <Section title="Logic Apps" onAdd={() => setValue({ ...value, logic_app_receivers: [...value.logic_app_receivers, { name: "", resource_id: "", endpoint: "", preserve_secret: false, use_common_alert_schema: true }] })}>{value.logic_app_receivers.map((item, i) => <EndpointRow key={i} name={item.name} nameLabel="Logic App receiver name" resourceId={item.resource_id} resourceLabel="Logic App" resourcePlaceholder="" endpoint={item.endpoint} preserveSecret={item.preserve_secret} common={item.use_common_alert_schema} resourceControl={<AzureResourceDropdown label="Logic App" connectionId={connectionId} subscriptionId={value.subscription_id} resourceGroup={value.resource_group} types={["microsoft.logic/workflows"]} value={item.resource_id} onChange={(resource_id) => update("logic_app_receivers", i, { resource_id })} />} onName={(name) => update("logic_app_receivers", i, { name })} onResource={(resource_id) => update("logic_app_receivers", i, { resource_id })} onEndpoint={(endpoint) => update("logic_app_receivers", i, { endpoint, preserve_secret: false })} onCommon={(use_common_alert_schema) => update("logic_app_receivers", i, { use_common_alert_schema })} onRemove={() => remove("logic_app_receivers", i)} />)}</Section>
    <Section title="Event Hubs" onAdd={() => setValue({ ...value, event_hub_receivers: [...value.event_hub_receivers, { name: "", subscription_id: value.subscription_id, resource_group: value.resource_group, tenant_id: "", namespace_name: "", event_hub_name: "", use_common_alert_schema: true }] })}>{value.event_hub_receivers.map((item, i) => <div key={i} className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Event Hub receiver name" placeholder="Name" value={item.name} onChange={(e) => update("event_hub_receivers", i, { name: e.target.value })} className={input} /><AzurePlacementFields connectionId={connectionId} subscriptionId={item.subscription_id} resourceGroup={item.resource_group} location="" showLocation={false} onChange={(patch) => update("event_hub_receivers", i, { subscription_id: patch.subscription_id ?? item.subscription_id, resource_group: patch.resource_group ?? item.resource_group, namespace_name: "", event_hub_name: "" })} /><input aria-label="Event Hub tenant ID" placeholder="Tenant GUID (optional)" value={item.tenant_id} onChange={(e) => update("event_hub_receivers", i, { tenant_id: e.target.value })} className={input} /><AzureResourceDropdown label="Event Hub namespace" connectionId={connectionId} subscriptionId={item.subscription_id} resourceGroup={item.resource_group} types={["microsoft.eventhub/namespaces"]} value={item.namespace_name} valueMode="name" onChange={(namespace_name) => update("event_hub_receivers", i, { namespace_name, event_hub_name: "" })} /><AzureResourceDropdown label="Event Hub" connectionId={connectionId} subscriptionId={item.subscription_id} resourceGroup={item.resource_group} types={["microsoft.eventhub/namespaces/eventhubs"]} value={item.event_hub_name} valueMode="name" onChange={(event_hub_name) => update("event_hub_receivers", i, { event_hub_name })} /><label className="flex items-center gap-1"><input type="checkbox" checked={item.use_common_alert_schema} onChange={(e) => update("event_hub_receivers", i, { use_common_alert_schema: e.target.checked })} /> Common schema</label><button onClick={() => remove("event_hub_receivers", i)} className="text-left text-red-600">Remove</button></div>)}</Section>
    <Section title="Automation Runbooks" onAdd={() => setValue({ ...value, automation_runbook_receivers: [...value.automation_runbook_receivers, { name: "", automation_account_id: "", runbook_name: "", webhook_resource_id: "", endpoint: "", preserve_secret: false, is_global_runbook: false, use_common_alert_schema: true }] })}>{value.automation_runbook_receivers.map((item, i) => <div key={i} className="space-y-2 rounded bg-gray-50 p-2"><div className="grid gap-2 sm:grid-cols-2"><input aria-label="Runbook receiver name" placeholder="Name" value={item.name} onChange={(e) => update("automation_runbook_receivers", i, { name: e.target.value })} className={input} /><input aria-label="Runbook name" placeholder="Runbook name" value={item.runbook_name} onChange={(e) => update("automation_runbook_receivers", i, { runbook_name: e.target.value })} className={input} /><AzureResourceDropdown label="Automation Account" connectionId={connectionId} subscriptionId={value.subscription_id} resourceGroup={value.resource_group} types={["microsoft.automation/automationaccounts"]} value={item.automation_account_id} onChange={(automation_account_id) => update("automation_runbook_receivers", i, { automation_account_id, webhook_resource_id: "" })} /><AzureResourceDropdown label="Automation webhook" connectionId={connectionId} subscriptionId={value.subscription_id} resourceGroup={value.resource_group} types={["microsoft.automation/automationaccounts/webhooks"]} value={item.webhook_resource_id} onChange={(webhook_resource_id) => update("automation_runbook_receivers", i, { webhook_resource_id })} /><input aria-label="Automation webhook URL" placeholder="HTTPS webhook URL" value={item.endpoint} onChange={(e) => update("automation_runbook_receivers", i, { endpoint: e.target.value, preserve_secret: false })} className={input} /><div className="flex gap-4"><label><input type="checkbox" checked={item.use_common_alert_schema} onChange={(e) => update("automation_runbook_receivers", i, { use_common_alert_schema: e.target.checked })} /> Common schema</label><label><input type="checkbox" checked={item.is_global_runbook} onChange={(e) => update("automation_runbook_receivers", i, { is_global_runbook: e.target.checked })} /> Global runbook</label><button onClick={() => remove("automation_runbook_receivers", i)} className="ml-auto text-red-600">Remove</button></div></div>{item.preserve_secret && <div className="text-[10px] text-amber-700">Signed webhook URL is hidden and will be preserved unless replaced.</div>}</div>)}</Section>
    <Section title="ITSM" onAdd={() => setValue({ ...value, itsm_receivers: [...value.itsm_receivers, { name: "", workspace_id: "", connection_id: "", region: "eastus", ticket_configuration: "{}", preserve_configuration: false }] })}>{value.itsm_receivers.map((item, i) => <div key={i} className="space-y-2 rounded bg-gray-50 p-2"><div className="grid gap-2 sm:grid-cols-2"><input aria-label="ITSM receiver name" placeholder="Name" value={item.name} onChange={(e) => update("itsm_receivers", i, { name: e.target.value })} className={input} /><AzureResourceDropdown label="Log Analytics workspace" connectionId={connectionId} subscriptionId={value.subscription_id} resourceGroup={value.resource_group} types={["microsoft.operationalinsights/workspaces"]} value={item.workspace_id} valueMode="workspace_id" onChange={(workspace_id, resource) => update("itsm_receivers", i, { workspace_id, region: resource?.location || item.region })} /><input aria-label="ITSM connection ID" placeholder="Connection ID" value={item.connection_id} onChange={(e) => update("itsm_receivers", i, { connection_id: e.target.value })} className={input} /><select aria-label="ITSM region" value={item.region} onChange={(e) => update("itsm_receivers", i, { region: e.target.value })} className={input}>{["centralindia", "japaneast", "southeastasia", "australiasoutheast", "uksouth", "westcentralus", "canadacentral", "eastus", "westeurope"].map((region) => <option key={region}>{region}</option>)}</select></div><textarea aria-label="ITSM ticket configuration" rows={4} disabled={item.preserve_configuration} value={item.preserve_configuration ? "Existing configuration is hidden and preserved." : item.ticket_configuration} onChange={(e) => update("itsm_receivers", i, { ticket_configuration: e.target.value })} className="w-full rounded border px-2 py-1.5 font-mono disabled:bg-gray-100" /><div className="flex items-center">{item.preserve_configuration && <button onClick={() => update("itsm_receivers", i, { preserve_configuration: false, ticket_configuration: "{}" })} className="text-indigo-700">Replace hidden configuration</button>}<button onClick={() => remove("itsm_receivers", i)} className="ml-auto text-red-600">Remove</button></div></div>)}</Section>
  </div>;
}

function EndpointRow({ name, nameLabel, resourceId, resourceLabel, resourcePlaceholder, resourceControl, endpoint, preserveSecret, common, extra, onName, onResource, onEndpoint, onCommon, onRemove }: { name: string; nameLabel: string; resourceId: string; resourceLabel: string; resourcePlaceholder: string; resourceControl?: ReactNode; endpoint: string; preserveSecret?: boolean; common: boolean; extra?: ReactNode; onName: (value: string) => void; onResource: (value: string) => void; onEndpoint: (value: string) => void; onCommon: (value: boolean) => void; onRemove: () => void }) {
  return <div className="space-y-2 rounded bg-gray-50 p-2"><div className="grid gap-2 sm:grid-cols-2"><input aria-label={nameLabel} placeholder="Name" value={name} onChange={(e) => onName(e.target.value)} className={input} />{resourceControl || <input aria-label={resourceLabel} placeholder={resourcePlaceholder} value={resourceId} onChange={(e) => onResource(e.target.value)} className={input} />}{extra}<input aria-label={`${nameLabel} endpoint`} placeholder="HTTPS signed callback URL" value={endpoint} onChange={(e) => onEndpoint(e.target.value)} className={input} /><label><input type="checkbox" checked={common} onChange={(e) => onCommon(e.target.checked)} /> Common schema</label><button onClick={onRemove} className="text-left text-red-600">Remove</button></div>{preserveSecret && <div className="text-[10px] text-amber-700">Signed endpoint is hidden and will be preserved unless replaced.</div>}</div>;
}

function Section({ title, onAdd, children }: { title: string; onAdd: () => void; children: ReactNode }) {
  return <section className="space-y-2 rounded-lg border p-3"><div className="flex items-center"><h3 className="font-semibold text-gray-800">{title}</h3><button onClick={onAdd} className="ml-auto rounded border px-2 py-1 text-[10px] text-indigo-700">+ Add</button></div>{children}</section>;
}
