"""Insight Pack file format: YAML frontmatter + a Markdown ``## AI instructions`` body.

A pack is portable as a single ``.pack.md`` file so it can be generated by the AI, edited
as raw text by power users, exported, and version-controlled. The frontmatter holds the
machine-readable, deterministic config (sources, scopes, filters, materiality, output);
the body holds the free-text AI instructions (with ``{{scope_label}}`` / ``{{lookback_hours}}``
placeholders the runtime fills in per assignment).

``parse`` is lenient (missing/garbled frontmatter degrades to sensible defaults) so a
half-written pack never hard-fails the runtime.
"""
from __future__ import annotations

from typing import Any

import yaml

# Canonical field defaults for a pack definition (the parsed, normalized shape).
DEFAULTS: dict[str, Any] = {
    "id": "",
    "name": "",
    "icon": "🧠",
    "category": "general",  # security | change | cost | identity | operations | general
    "description": "",
    "sources": ["change_explorer"],
    "supported_scopes": ["workload", "subscription", "tenant"],
    "lookback_hours": 24,
    "filters": {"categories": [], "operations": [], "min_risk": "low"},
    "materiality": {"notify_threshold": "notable", "always_notify_if": []},
    "output": {"format": ["bullets", "table"],
               "table_columns": ["time", "workload", "change", "risk", "owner", "recommended_action"]},
    "instructions": "",
    "enabled": True,
    "builtin": False,
    "created_by": "",
    "created_at": "",
    "updated_at": "",
    "snoozed_until": "",  # ISO instant; runtime mute state (kept out of the portable .pack.md)
    "pinned": False,       # organizational state — pin to the Library top section (not in .pack.md)
    "collection_ids": [],  # user-defined collection membership (not in .pack.md)
}

VERDICTS = ("nothing_notable", "notable", "urgent")
VERDICT_RANK = {"nothing_notable": 0, "notable": 1, "urgent": 2}
MIN_RISK = ("low", "medium", "high", "critical")

_BODY_HEADING = "## AI instructions"

# Frontmatter keys (everything except the free-text instructions body).
_FRONT_KEYS = (
    "id", "name", "icon", "category", "description", "sources", "supported_scopes",
    "lookback_hours", "filters", "materiality", "output", "enabled", "builtin",
    "created_by", "created_at", "updated_at",
)


def normalize(raw: dict[str, Any]) -> dict[str, Any]:
    """Coerce a partial pack dict into the canonical shape with valid, bounded values."""
    p = {**DEFAULTS, **{k: v for k, v in (raw or {}).items() if v is not None}}
    # Deep-merge the nested config blocks so a partial override keeps the other keys.
    p["filters"] = {**DEFAULTS["filters"], **(raw.get("filters") or {})}
    p["materiality"] = {**DEFAULTS["materiality"], **(raw.get("materiality") or {})}
    p["output"] = {**DEFAULTS["output"], **(raw.get("output") or {})}

    p["sources"] = [str(s) for s in (p.get("sources") or []) if s] or ["change_explorer"]
    p["supported_scopes"] = [s for s in (p.get("supported_scopes") or [])
                             if s in ("tenant", "subscription", "workload")] or ["workload"]
    try:
        p["lookback_hours"] = max(1, min(24 * 30, int(p.get("lookback_hours") or 24)))
    except (TypeError, ValueError):
        p["lookback_hours"] = 24
    if p["filters"].get("min_risk") not in MIN_RISK:
        p["filters"]["min_risk"] = "low"
    if p["materiality"].get("notify_threshold") not in VERDICTS:
        p["materiality"]["notify_threshold"] = "notable"
    p["materiality"]["always_notify_if"] = [str(x) for x in (p["materiality"].get("always_notify_if") or [])]
    fmt = [f for f in (p["output"].get("format") or []) if f in ("bullets", "table")]
    p["output"]["format"] = fmt or ["bullets", "table"]
    p["instructions"] = str(p.get("instructions") or "")
    p["name"] = str(p.get("name") or "")[:200]
    p["enabled"] = bool(p.get("enabled", True))
    p["builtin"] = bool(p.get("builtin", False))
    p["snoozed_until"] = str(p.get("snoozed_until") or "")
    p["pinned"] = bool(p.get("pinned", False))
    p["collection_ids"] = [str(c) for c in (p.get("collection_ids") or []) if c]
    return p


def to_markdown(pack: dict[str, Any]) -> str:
    """Serialize a pack dict to the ``.pack.md`` text form (frontmatter + instructions body)."""
    p = normalize(pack)
    front = {k: p[k] for k in _FRONT_KEYS if k in p}
    fm = yaml.safe_dump(front, sort_keys=False, allow_unicode=True, default_flow_style=False).strip()
    body = (p.get("instructions") or "").strip()
    return f"---\n{fm}\n---\n\n{_BODY_HEADING}\n\n{body}\n"


def parse(text: str) -> dict[str, Any]:
    """Parse ``.pack.md`` text into a normalized pack dict. Lenient: bad/missing frontmatter
    degrades to defaults, and everything after the frontmatter (or the whole text when there
    is none) becomes the instructions body."""
    text = text or ""
    front: dict[str, Any] = {}
    body = text
    if text.lstrip().startswith("---"):
        stripped = text.lstrip()
        end = stripped.find("\n---", 3)
        if end != -1:
            fm_text = stripped[3:end].strip()
            body = stripped[end + 4:]
            try:
                loaded = yaml.safe_load(fm_text)
                if isinstance(loaded, dict):
                    front = loaded
            except yaml.YAMLError:
                front = {}
    # Drop the "## AI instructions" heading from the body if present.
    b = body.strip()
    low = b.lower()
    idx = low.find(_BODY_HEADING.lower())
    if idx != -1:
        b = b[idx + len(_BODY_HEADING):].strip()
    merged = {**front, "instructions": b}
    return normalize(merged)
