"""FMEA (Failure Mode and Effects Analysis) feature package.

An *FMEA document* belongs to an architecture (like a Know-Me) and is generated by AI from
that architecture's Memory + real Azure scope + posture evidence. It holds MULTIPLE tables
(one per subsystem / process step), each a list of rows scored on Severity, Occurrence and
Detection (1-10). The Risk Priority Number (RPN = Severity x Occurrence x Detection) is
always derived server-side — never trusted from the client or the model.
"""
